# See _subsite_config.yml for default settings

title: Help

description: "Help Documentation for Caseflow"

# https://mmistakes.github.io/minimal-mistakes/docs/configuration/#site-base-url
url: "https://department-of-veterans-affairs.github.io"
baseurl: "/caseflow/help" # required for themes to work in GH Pages for this repo

source: __help
destination: _site/help

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

# -------- minimal-mistakes-jekyll configuration
# https://github.com/mmistakes/minimal-mistakes/blob/master/_config.yml
minimal_mistakes_skin: air
locale: "en-US"
breadcrumbs: true
search: true
search_full_content: true
# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
sidebar:
  - title: "Title"
    text: "Some text here."
  - title: "Another Title"
    text: "More text here."
atom_feed:
  hide: true
