# See _subsite_config.yml for default settings

# Use a subsite for Task Trees because there are a lot of files and
# searching through those files are not needed.
title: Task Trees

description: "Task Trees Documentation for Caseflow"
baseurl: "/caseflow/tasktrees" # required for themes to work in GH Pages for this repo
source: __tasktrees
destination: _site/tasktrees

# remote_theme: pages-themes/modernist@v0.2.0
# remote_theme: pmarsceill/just-the-docs # https://pmarsceill.github.io/just-the-docs/docs/configuration/
# defaults:
#   -
#     scope:
#       path: "docs-*" # an empty string here means all files in the project
#     values:
#       layout: "default"
#       nav_exclude: true
#       search_exclude: true

