name: install_node_dependencies


runs:
  using: composite
  steps:
    - name: restore yarn cache
      uses: actions/cache@v3
      with:
        key: dot-cache-yarn-v2-{{ arch }}-{{ checksum "client/yarn.lock" }}
      restore-keys:
        dot-cache-yarn-v2-{{ arch }}-{{ checksum "client/yarn.lock" }}
      shell: bash
    - name: yarn install
      run: ~/project/ci-bin/capture-log "cd client && yarn install --frozen-lockfile"
      shell: bash
    - name: Save Cache
      uses: actions/cache@v3
      with:
        key: dot-cache-yarn-v2-{{ arch }}-{{ checksum "client/yarn.lock" }}
        paths:
          - ~/.cache/yarn
          - public/assets
          - tmp/cache/assets/sprockets
      shell: bash
