name: install_ruby_dependencies

on:
  workflow_call:


jobs:
  install_ruby_dependencies:
      description: "Install Ruby Dependencies"
      runs-on: ubuntu-latest
      steps:
      - name: Ruby version
        run: ruby -v
      - name: Configure Bundler
        run: |
          echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
          source $BASH_ENV
          gem install bundler
      - name: Restore Cache
        uses: actions/cache@v3
        with:
          key: v3-app-lambdas-{{ checksum "hello-world-test/package-lock.json" }}
          restore-keys:
            v3-app-lambdas-{{ checksum "hello-world-test/package-lock.json" }}
      - name: Bundle install
        run: bundle install --path vendor/bundle
      - name: Save Cache
        uses: actions/cache@v3
        with:
          key: v3-app-lambdas-{{ checksum "hello-world-test/package-lock.json" }}
          paths:
              - ~/project/vendor/bundle
