name: Wait For Databases

inputs:
  DISABLE_FACTORY_BOT_INITIALIZERS:
    default: 1
    required: true

runs:
  using: composite
  steps:
    - name: "Wait for database"
      run: dockerize -wait tcp://localhost:5432 -timeout 1m
      shell: bash
    - name: "Wait for FACOLS"
      run: ~/project/ci-bin/capture-log "bundle exec rake local:vacols:wait_for_connection"
      shell: bash
