name: 'Linter'

# on:
#   workflow_call:
on:
  workflow_call:

jobs:
  linter:
    runs-on: ubuntu-latest
    container:
      image: 008577686731.dkr.ecr.us-gov-west-1.amazonaws.com/gaimg-ruby:2.7.3-ga-browsers
      credentials:
          username: AWS
          password: ${{ secrets.ECR_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Ruby Dependencies
        run: |
          ruby -v
          BUNDLER_V=$(cat ./Gemfile.lock | tail -1 | tr -d " ")
          echo $BUNDLER_V
          gem install bundler:$BUNDLER_V
          bundle install --path vendor/bundle

      - name: Install Node Dependencies
        run: ./ci-bin/capture-log "cd client && yarn install --frozen-lockfile"

      - name: Danger
        run: ./ci-bin/capture-log "bundle exec danger"

      - name: Lint
        run:  ./ci-bin/capture-log "bundle exec rake lint"

      - name: Security
        run:  ./ci-bin/capture-log "bundle exec rake security"

      - name: Concatenate all logs
        run: ./ci-bin/concatenate-log.rb >> ./all_logs.log

      # TODO: Not sure if this is needed with GH Actions
      - name: Store concatenated logs
        run: ./all_logs.log
