name: 'Linter'

on:
  workflow_call:

jobs:
  linter:
    runs-on: ubuntu-latest
    # TODO: Change image if needed
    container:
      image: 008577686731.dkr.ecr.us-gov-west-1.amazonaws.com/gaimg-ruby:2.7.3-ga-browsers

    steps:
      - name: Checkout
        uses: actions/checkout@v2

       - name: Install Ruby Dependencies
        run: |
          ruby -v
          BASH_ENV="Bash"
          echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> "$BASH_ENV"
          export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")
          gem install bundler
          bundle install --path vendor/bundle

      - name: Install Node Dependencies
        run: ./ci-bin/capture-log "cd client && yarn install --frozen-lockfile"

      - name: Danger
        run: ~/project/ci-bin/capture-log "bundle exec danger"

      - name: Lint
        run:  ~/project/ci-bin/capture-log "bundle exec rake lint"

      - name: Security
        run:  ~/project/ci-bin/capture-log "bundle exec rake security"

      - name: Concatenate all logs
        run: ~/project/ci-bin/concatenate-log.rb >> ~/all_logs.log

      # TODO: Not sure if this is needed with GH Actions
      - name: Store concatenated logs
        run: ~/all_logs.log
