name: Reusable workflow example 2

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string

jobs:
  install-node:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
     - name: Install Node
       uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
