name: Reusable workflow example

on:
  workflow_dispatch:
  push:
    branches: f-gh-migration

jobs:
  validate-demo:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11.7
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: password
          POSTGRES_DB: caseflow_certification_test
        ports:
        - 5432:5432
      redis:
        image: redis:4.0.10
        ports:
        - 6379:6379
      facols:
        image: 008577686731.dkr.ecr.us-gov-west-1.amazonaws.com/facols:latest
    container:
      image: 008577686731.dkr.ecr.us-gov-west-1.amazonaws.com/gaimg-ruby:2.7.3-ga-browsers
      env:
          DBUS_SESSION_BUS_ADDRESS: /dev/null
          RAILS_ENV: test
          NODE_ENV: test
          BUNDLE_PATH: vendor/bundle
          COVERAGE_DIR: /home/circleci/coverage
          POSTGRES_HOST: localhost
          POSTGRES_USER: root
    steps:
      - uses: actions/checkout@v3
      - name: Install dpackage
        run: apt install dpkg
      - name: Install chromium
        run: |
          VERSION_STRING="106.0.5249.119"
          wget "https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_${VERSION_STRING}_amd64.deb"
          sudo dpkg -i "google-chrome-stable_${VERSION_STRING}_amd64.deb"
      - name: setup testfiles directory
        run: ~/project/ci-bin/capture-log "mkdir -p ~/project/tmp/testfiles"
      - name: install node dependencies
        uses: ./utils/install_node_dependencies.yml



